In [1]:
import pandas as pd

#read csv file
df = pd.read_csv('players_20.csv' , encoding = 'unicode_escape')

#set index
#df = df.set_index('short_name') #creates a copy so we need to overwrite  
df.set_index('short_name',inplace=True)

#select columns
df = df[['long_name',	'age',	'dob',	'height_cm',	'weight_kg',	'nationality',	'club']]

#show dataframe
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel AndrÃ©s Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,AtlÃ©tico Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,éµå¸,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,å¼ å¨,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,æ±ªæµ·å¥,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,æ½åæ,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

1 sample()

In [2]:
#extract 10 random elements from the "nationality" col

df['nationality'].sample(10)

short_name
Nathan                       Brazil
T. ChorÃ½            Czech Republic
Porphirinho                  Brazil
A. Al Yami             Saudi Arabia
A. Weis                     Germany
D. Mihailovic         United States
E. Aguirre                   Mexico
J. Jones                    England
Claude GonÃ§alves          Portugal
Guo Quanbo                 China PR
Name: nationality, dtype: object

In [3]:
#extract a random 20% sample of the dataframe
df.sample(frac=0.2)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Camacho,Ignacio Camacho Barnola,29,1990-05-04,183,75,Spain,VfL Wolfsburg
G. MacKenzie,Gary MacKenzie,33,1985-10-15,191,83,Scotland,St. Mirren
M. Klich,Mateusz Klich,29,1990-06-13,183,82,Poland,Leeds United
J. MartÃ­nez,JosÃ© JoaquÃ­n MartÃ­nez Valadez,32,1987-02-22,177,67,Mexico,Monarcas Morelia
D. Chambost,Dylan Chambost,21,1997-08-19,177,70,France,ESTAC Troyes
...,...,...,...,...,...,...,...
C. DÃ­az,Camilo DÃ­az,21,1997-08-02,182,73,Colombia,Rionegro Ãguilas
Park Sung Min,ë°ì±ë¯¼ Sung Min Park,20,1998-12-12,181,77,Korea Republic,FC Seoul
M. Cestor,Mike Cestor,27,1992-04-30,178,78,DR Congo,CFR Cluj
Carlos ManÃ©,Carlos Manuel Cardoso ManÃ©,25,1994-03-11,173,68,Portugal,Rio Ave FC
Rafa Tresaco,Rafael Tresaco Blasco,18,2000-08-24,178,68,Spain,Racing Santander

In [4]:
#upsample increase the sampling rate frac>1 (Note replace param has to be true) 
df.sample(frac=2, replace=True)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Han Seok Hee,SeokHee Han,23,1996-05-16,170,66,Korea Republic,Suwon Samsung Bluewings
R. SÃ¡nchez,Richard SÃ¡nchez,23,1996-03-29,172,71,Paraguay,Paraguay
C. Zesiger,CÃ©dric Zesiger,21,1998-06-24,194,90,Switzerland,BSC Young Boys
F. Cerda,FabiÃ¡n Alfredo Cerda ValdÃ©s,30,1989-02-07,183,83,Chile,CD Palestino
R. Ofosu,Reagy Ofosu,27,1991-09-20,175,76,Germany,FC BotoÅani
...,...,...,...,...,...,...,...
Tano Bonnin,Cayetano BartolomÃ© BonnÃ­n VÃ¡squez,29,1990-06-30,186,76,Dominican Republic,UD AlmerÃ­a
O. Malik,Osama Malik,28,1990-09-30,185,75,Australia,Perth Glory
P. Pentz,Patrick Pentz,22,1997-01-02,182,81,Austria,FK Austria Wien
L. Galicia,Luis Galicia,19,2000-04-12,178,73,Mexico,Tiburones Rojos de Veracruz
Rafael Defendi,Rafael Garcia Tonioli Defendi,35,1983-12-22,191,88,Brazil,FamalicÃ£o